# Generated by Django 5.2 on 2025-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_issue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='semester',
            field=models.CharField(choices=[('semester 1', 'SEMESTER 1'), ('semester 2', 'SEMESTER 2')], max_length=50),
        ),
    ]
